"use client";

import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext({ lang: "en", toggle: () => {} });

export const translations = {
  en: {
    // Sidebar
    appTagline: "Your singing coach",
    nav: {
      dashboard: "Dashboard",
      learningPaths: "Learning Paths",
      practice: "Practice",
      voiceAnalysis: "Voice Analysis",
      routinePlanner: "Routine Planner",
      learningPhases: "Learning Phases",
      foundation: "Foundation",
      technique: "Technique & Expression",
      performance: "Performance",
      songLibrary: "Song Library",
      virtualStage: "Virtual Stage",
    },
    // Dashboard header
    welcomeBack: "Welcome back",
    phaseJourney: (phase) => `Phase ${phase} of your 京剧 journey`,
    // Stats cards
    dayStreak: "Day Streak",
    weeklyGoal: "Weekly Goal",
    practiceMinutes: "Practice Minutes",
    avgScore: "Avg Score",
    // Dashboard sections
    activeMission: "Active Mission: Foundation Master",
    activeMissionDesc: (phase) =>
      `Finish all Phase ${phase} levels to master the basics and unlock the next level.`,
    goToPhase: (phase) => `Go to Phase ${phase}`,
    continuePhase: (phase) => `Continue Phase ${phase}`,
    startTodayPractice: "Start Today's Practice",
    browseSongs: "Browse 唱段",
    recentActivity: "Recent Activity",
    noRecentActivity: "No recent activity. Start practicing!",
    completed: "Completed",
    score: "Score",
    yourProgress: "Your Progress",
    weeklyPractice: "Weekly Practice",
    minutes: "min",
    of: "of",
    goal: "goal",
    // Phase names in sidebar
    phase1Title: "Foundation",
    phase2Title: "Technique & Expression",
    phase3Title: "Performance",
    // Quick actions
    quickActions: "Quick Actions",
    yourLearningPath: "Your Learning Path",
    startPracticeLabel: "Start Practice",
    voiceExercises: "Voice exercises",
    routinePlannerLabel: "Routine Planner",
    createPracticePlan: "Create practice plan",
    learningPathsLabel: "Learning Paths",
    chooseApproach: "Choose your approach",
    browseSongsLabel: "Browse Songs",
    findSongs: "Find songs to practice",
    virtualStageLabel: "Virtual Stage",
    performSong: "Perform a song",
    minutesThisWeek: "Minutes This Week",
    averageScore: "Average Score",
    viewAll: "View all",
    // Language toggle label
    toggleLabel: "中文",

    // Dashboard learning path config (banner summaries)
    lpc: {
      structured: {
        description: "Continue your step-by-step Jingju journey — 丹田 breath, 咬字归韵, and systematic phase progression.",
        action: (phase) => `Continue Phase ${phase}`,
      },
      intensive: {
        description: "Keep up the daily 旦角 training! Focus on falsetto control, 行腔 fluency, and 花腔 ornamentation.",
        action: "Start Today's Practice",
      },
      performance: {
        description: "Focus on 生角 唱段 and stage presence. Apply your 二黄/西皮 technique to classic Jingju arias.",
        action: (phase) => phase >= 2 ? "Browse 唱段" : "Start Practice",
      },
      adaptive: {
        description: "Your AI-recommended 京剧 routine is ready! Tailored exercises targeting your current 咬字 and 行腔 weaknesses.",
        action: "View Routine",
      },
      flexible: {
        description: "Zero-pressure 京剧 exploration. Choose any 唱段 or exercise and discover your role type at your own pace.",
        action: "Explore 唱段",
      },
    },

    // Settings page
    settings: {
      title: "Settings",
      profileSettings: "Profile Settings",
      manageProfile: "Manage your profile information",
      name: "Name",
      emailAddress: "Email Address",
      experienceLevel: "Experience Level",
      selectExperience: "Select experience level",
      beginner: "Beginner",
      intermediate: "Intermediate",
      advanced: "Advanced",
      saving: "Saving...",
      saveChanges: "Save Changes",
      resetPassword: "Reset Password",
      updateSecurity: "Update your account security",
      newPassword: "New Password",
      passwordPlaceholder: "Min. 8 chars, A-Z, a-z, 0-9, !@#",
      appearance: "Appearance",
      customizeApp: "Customize the look of the app",
      darkMode: "Dark Mode",
      lightMode: "Light Mode",
      switchTheme: "Switch between light and dark themes",
      accountActions: "Account Actions",
      manageAccount: "Manage your account access and data",
      signOut: "Sign Out",
      signOutDesc: "Log out of your current session",
      resetProgress: "Reset Progress",
      resetProgressDesc: "Delete all your practice history and start over",
      resetAllProgress: "Reset All Progress",
      resetConfirm: "Are you sure you want to reset all progress? This cannot be undone.",
      savedTitle: "Settings saved",
      savedDesc: "Your profile has been updated.",
      errorTitle: "Error",
      errorDesc: "Failed to save settings. Please try again.",
      progressResetTitle: "Progress reset",
      progressResetDesc: "Your learning progress has been reset.",
      passwordUpdatedTitle: "Password updated",
      passwordUpdatedDesc: "Your password has been changed successfully.",
      invalidPasswordTitle: "Invalid password",
      passwordErrorDesc: "Failed to update password. Please try again.",
    },

    // Learning Paths page
    lp: {
      pageTitle: "Choose Your",
      pageTitleHighlight: "Path",
      pageDesc: "Select the 京剧 training methodology that matches your role type, experience level, and artistic goals. Each path is rooted in the authentic Peking Opera (京剧) tradition.",
      backToDashboard: "Back to Dashboard",
      recommendedFor: (level) => `Recommended for ${level}`,
      recommendedDesc: (name) => `Based on your experience level, we recommend the ${name} approach to maximize your learning potential.`,
      recommended: "Recommended",
      focusAreas: "Focus Areas:",
      approach: "Approach:",
      benefits: "Benefits:",
      selected: "Selected",
      selectPath: "Select This Path",
      readyToStart: "Ready to start your learning journey?",
      configuring: "Configuring...",
      launchPath: "Launch Path",
      notSureTitle: "Not sure which 京剧 path to choose?",
      notSureDesc1: "No need to worry — you can switch paths at any time. If you are new to Peking Opera or Chinese classical singing, start with Jingju Foundation to build proper technique from the ground up. If you already have some experience and want personalized coaching, try the Adaptive AI Coach.",
      notSureDesc2: "Every path is grounded in authentic Jingju technique — 丹田 breath support, 咬字归韵, 行腔, 拖腔, 韵味, and 神韵. Choose the approach that excites you most and begin your journey toward the 京剧 stage.",
      selectedToastTitle: "Learning path selected!",
      selectedToastDesc: (name) => `You've chosen the ${name} approach. Let's start your journey!`,
      errorTitle: "Error",
      errorDesc: "Failed to save learning path. Please try again.",
      paths: {
        structured: {
          name: "Jingju Foundation",
          description: "A systematic journey through Peking Opera vocal fundamentals — from breath support and articulation to melodic phrasing and aesthetic flavor",
          duration: "12-16 weeks",
          difficulty: "Beginner to Advanced",
          focus: ["Jingju Basics", "Rhythmic Training", "Phase Progression"],
          approach: "Linear progression through Jingju phases: Foundation → Technique → Repertoire, with clear milestones at each stage",
          benefits: ["Builds authentic Peking Opera technique", "Covers breath, articulation, and melisma", "Structured female/male role voice training", "Ideal for complete beginners to Jingju"],
        },
        intensive: {
          name: "Dan Role Intensive",
          description: "Fast-track female-role mastery — daily high-commitment sessions focused on the stylized Dan voice, falsetto control, and melodic phrasing",
          duration: "4-6 weeks",
          difficulty: "Intermediate",
          focus: ["Dan Role Voice", "Falsetto Control", "Daily Drills"],
          approach: "Concentrated daily practice targeting the most critical Dan role techniques: falsetto register, register transitions, vibrato control, and ornamentation",
          benefits: ["Fast-track Dan role voice development", "Intensive falsetto register training", "Daily melodic phrasing and melisma drills", "Classic female-role style orientation"],
        },
        performance: {
          name: "Sheng Role Intensive",
          description: "Deep-dive into male-role vocal mastery — mature Sheng chest resonance, lyrical tone, and the dignified Erhuang/Xipi phrasing",
          duration: "8-12 weeks",
          difficulty: "All Levels",
          focus: ["Sheng Role Technique", "Erhuang / Xipi", "Dramatic Delivery"],
          approach: "Master Sheng role vocal technique through iconic arias — chest-mix voice, rapid articulation, and the noble aesthetic flavor of male Jingju",
          benefits: ["Authentic mature/young Sheng voice development", "Erhuang and Xipi melodic mastery", "Dramatic recitative and heightened speech training", "Repertoire-ready in classic Sheng arias"],
        },
        adaptive: {
          name: "Adaptive AI Coach",
          description: "Personalized AI coaching that targets your specific Peking Opera weaknesses — whether articulation, melodic phrasing, aesthetic flavor, or breath support",
          duration: "Flexible",
          difficulty: "All Levels",
          focus: ["Weakness Targeting", "AI-Guided", "Jingju Metrics"],
          approach: "AI analyzes your Jingju-specific metrics (pitch accuracy, articulation clarity, vibrato, aesthetic flavor) and creates custom exercise sequences",
          benefits: ["Tailored to your role type (Dan/Sheng/Jing)", "Targets your weakest Jingju areas", "Smart coaching with ensemble awareness", "Optimized pace for your voice"],
        },
        flexible: {
          name: "Aria Performance First",
          description: "Learn Peking Opera technique through singing actual arias — from classic female-role pieces to heroic male-role repertoire",
          duration: "Self-Paced",
          difficulty: "All Levels",
          focus: ["Aria-Driven", "Stage Presence", "Self-Directed"],
          approach: "Master Jingju technique through actual classic arias — technique serves the character and drama, not the reverse",
          benefits: ["Immediate aria application", "Peking Opera stage confidence", "Character and spirit development", "Flexible self-paced exploration"],
        },
      },
    },

    // Analysis page
    analysis: {
      title: "Voice Analysis",
      subtitle: "Upload your recordings for deep acoustic analysis and professional feedback.",
      chooseFile: "Choose an audio file",
      dragDrop: "Drag and drop your vocal recording here, or click to browse. Supports WAV, MP3, M4A, and WEBM.",
      invalidFile: "Please select a valid audio file.",
      invalidFileDrop: "Please drop a valid audio file.",
      analyzeVoice: "Analyze Voice",
      analyzingTitle: "Analyzing Your Vocals",
      analyzingDesc: "Our AI is processing your pitch, tone, and technique. This usually takes 5-10 seconds.",
      analysisComplete: "Analysis Complete",
      resultsGenerated: (date) => `Results generated on ${date}`,
      analyzeNewFile: "Analyze New File",
      expertInsights: "Expert Insights",
      defaultSuggestions: [
        "Your pitch accuracy remains consistent throughout the recording.",
        "Tone stability is strong, showing good vocal cord control.",
        "Try to focus on breath support during the higher passages.",
      ],
      openPractice: "Open Practice Routine",
      howItWorks: "How it works",
      howItWorksDesc: "Professional analysis powered by signal processing",
      steps: [
        { title: "Acoustic Metric Engine", desc: "We extract fundamental frequency (F0) and spectral features to measure pitch and tone." },
        { title: "LLM Vocal Coaching", desc: "Our AI model analyzes recordings to provide natural language feedback and suggestions." },
        { title: "Progressive Tracking", desc: "Each analysis is saved to your profile to help you track your vocal growth over time." },
      ],
      bestTips: "Best Recording Tips",
      tips: [
        "Use a quiet environment with minimal background noise.",
        "Stay roughly 6-12 inches away from your microphone.",
        "Sing clearly and naturally.",
      ],
    },

    // Routine Planner page
    routine: {
      title: "Practice Routine Planner",
      subtitle: "Generate personalized practice routines based on your goals and progress",
      generateTitle: "Generate Routine",
      generateDesc: "Customize your practice session",
      duration: "Duration",
      durationTip: "Recommended: 20-40 minutes per session",
      focusAreas: "Focus Areas",
      focusAreasTip: "Leave empty for balanced routine",
      generating: "Generating...",
      generate: "Generate Routine",
      yourRoutines: "Your Practice Routines",
      minuteSession: (n) => `${n}-Minute Practice Session`,
      exercisesCount: (total, completed) => `${total} exercises • ${completed} completed`,
      progress: "Progress",
      start: "Start",
      noRoutines: "No routines yet",
      noRoutinesDesc: "Generate your first practice routine to get started with structured practice sessions",
      categories: {
        warmup: "Warmup",
        technique: "Technique",
        performance: "Performance",
      },
    },

    // Phase page
    phase: {
      pageTitle: (id, name) => `Phase ${id}: ${name}`,
      complete: "Complete",
      notAvailable: "Phase Not Available",
      notAvailableDesc: "Complete previous phases to unlock this content.",
      backToDashboard: "Back to Dashboard",
      finalTest: (id) => `Phase ${id} Final Test`,
      availableNow: "Available Now",
      finalTestDesc: "Apply everything you've learned in this phase. This performance will be analyzed for your final phase grade.",
      startTest: "Start Phase Test",
      exercises: "Exercises",
      exercisesCompleted: (done, total) => `${done}/${total} completed`,
      noExercises: "No exercises available yet. Check back soon!",
      whatYoullLearn: "What You'll Learn",
      nextPhase: "Next Phase",
      goToPhase: (n) => `Go to Phase ${n}`,
    },

    // Practice page
    practice: {
      titleSong: (title) => `Practice: ${title}`,
      titleVoice: "Voice Practice",
      subtitleSong: (artist, genre, key, bpm) => `${artist} • ${genre} • ${key} • ${bpm} BPM`,
      subtitleVoice: "Record your voice and get instant AI-powered feedback",
      important: "Important:",
      micWarning: "Place your microphone nearby before recording. Try to record your voice for more than 20 seconds for better AI analysis results.",
      songPracticeMode: "Song Practice Mode",
      difficulty: "Difficulty",
      vocalRange: "Vocal Range",
      key: "Key",
      tempo: "Tempo",
      practiceTipsTitle: "💡 Practice Tips:",
      practiceTips: (key, bpm) => [
        "Warm up your voice before singing",
        `Focus on matching the key (${key})`,
        `Keep the tempo steady at ${bpm} BPM`,
        "Record multiple takes to track your progress",
      ],
      pathModes: {
        flexible: { title: "唱段先行 Mode", desc: "Choose any 唱段 or exercise that interests you today. No pressure — explore 京剧 freely!" },
        competitive: { title: "Challenge Mode Active", desc: "Complete exercises to earn achievements and level up!" },
        intensive: { title: "旦角强化", desc: "Stay focused on your daily 旦角 training. 咬字 and 行腔 consistency is key!" },
        performance: { title: "生角强化", desc: "Focus on 生角 唱段 and stage skills. Build your 二黄/西皮 repertoire!" },
        adaptive: { title: "AI 自适应京剧教练", desc: "AI-powered 京剧 recommendations based on your 咬字, 行腔, and 韵味 progress." },
        structured: { title: "京剧基础", desc: "Follow the progressive Jingju path through each phase systematically." },
      },
      singTitle: (title) => `Sing: ${title}`,
      voiceRecorder: "Voice Recorder",
      practiceDesc: "Practice singing this song and get AI feedback on your performance",
      selectExercise: "Select an exercise or record freely",
      instructions: "Instructions",
      demo: "Demo",
      upload: "Upload",
      analyzing: "Analyzing...",
      analyzeVoice: "Analyze Voice",
      analysisResults: "Analysis Results",
      aiCoach: "AI Vocal Coach Analysis",
      defaultFeedback: "Your performance has been evaluated. Focus on consistent technique and breath support for your next take.",
      technicalStrengths: "Technical Strengths",
      detectedMistakes: "Detected Technical Mistakes",
      suggestions: "Actionable Suggestions",
      tryAgain: "Try Again",
      exercises: "Exercises",
      practiceSavedTitle: "Practice saved!",
      practiceSavedDesc: "Your streak has been updated.",
      sessionExpiredTitle: "Session expired",
      sessionExpiredDesc: "Please sign in again to save your progress.",
      exerciseNotFoundTitle: "Exercise not found",
      exerciseNotFoundDesc: "This exercise no longer exists. Please select a new one.",
      saveFailedTitle: "Could not save progress",
      saveFailedDesc: "Your practice was analysed but not recorded. Try again.",
    },

    // Learning Path Welcome page
    lpWelcome: {
      confirmed: "Selection Confirmed",
      welcomeTo: (title) => `Welcome to the ${title} Path`,
      whatsAhead: "What's ahead:",
      startTraining: "Start Your First Training",
      changePath: "Change Path",
      goToDashboard: "Go to Dashboard",
      paths: {
        structured: {
          description: "Step-by-step Peking Opera foundation: 丹田 breath, 咬字归韵, 旦角/生角 voice introduction, and pentatonic pitch training.",
          highlights: ["丹田 breath & 咬字 drills", "Perfect for Jingju beginners", "Systematic 三阶段 progression"],
        },
        intensive: {
          description: "Fast-track 旦角 mastery with daily high-commitment sessions targeting falsetto control, 行腔, and 花腔 ornamentation.",
          highlights: ["Daily 旦角 falsetto training", "Intensive 行腔 and 拖腔 drills", "梅派/程派 style development"],
        },
        performance: {
          description: "Deep-dive into 生角 vocal mastery — 老生 chest resonance, 二黄/西皮 phrasing, and the dignified delivery of male Jingju roles.",
          highlights: ["老生/小生 voice development", "二黄 and 西皮 melodic mastery", "Repertoire-ready classic arias"],
        },
        adaptive: {
          description: "Personalized AI path that targets your specific Jingju weaknesses — 咬字, 行腔, 韵味, or breath support.",
          highlights: ["AI-driven 京剧 recommendations", "Targets your weakest techniques", "Role-type (旦/生/净) awareness"],
        },
        flexible: {
          description: "Learn Peking Opera technique through singing actual 唱段 — from 苏三起解 to 霸王别姬 to 锁麟囊, at your own pace.",
          highlights: ["Classic 唱段-driven learning", "Self-directed 京剧 exploration", "Character and 神韵 development"],
        },
      },
    },

    // Perform (Virtual Stage) page
    perform: {
      notAvailable: "Not Available Yet",
      notAvailableDesc: "Reach Phase 3 (Advanced) to unlock the Virtual Stage.",
      backToDashboard: "Back to Dashboard",
      finalTestTitle: (phase) => `Phase ${phase} Final Test`,
      stageTitle: "Virtual Performance Stage",
      finalTestDesc: (title) => `Demonstrate your skills by performing "${title}"`,
      stageDesc: "Practice performing with simulated audience feedback",
      finalTestBadge: "FINAL TEST",
      micWarning: "Place your microphone nearby before recording. Try to record your voice for more than 20 seconds for better AI analysis results.",
      important: "Important:",
      readyToSing: (title) => `Ready to sing "${title}"?`,
      readyToPerform: "Ready to Perform?",
      songSubtitle: (artist, genre) => `${artist} - ${genre}`,
      stepOnStage: "Step onto the virtual stage and show your skills",
      takeStage: "Take the Stage",
      micLevel: "Mic Level",
      tooQuiet: "🔇 Too Quiet",
      tooLoud: "🔊 Too Loud",
      goodLevel: "✓ Good",
      endPerformance: "End Performance",
      analyzingTitle: "Analyzing Performance",
      analyzingDesc: "The audience is listening...",
      audienceReaction: "Audience Reaction",
      retry: "Retry",
      yourRecording: "Your Recording",
      performAgain: "Perform Again",
      phaseComplete: "Phase Complete!",
      phaseUnlocked: (phase) => `You've successfully unlocked Phase ${phase}`,
      goToPhase: (phase) => `Go to Phase ${phase}`,
      performanceScore: "Performance Score",
      performanceTips: "Performance Tips",
      tips: [
        "开嗓 — warm up your voice with gentle glides before starting",
        "丹田呼吸 — breathe from the lower abdomen, not the chest",
        "咬字 — attack each character's consonant cleanly at the start",
        "韵味 — inhabit your role type (旦/生/净) and let the emotion shape the tone",
        "叫好 — imagine a 戏迷 audience ready to shout \"好！\" at your best moment",
      ],
    },

    // Songs page
    songs: {
      title: "京剧唱段库 (Aria Library)",
      subtitle: "Find classic 唱段 that match your role type (旦角/生角/净角) and phase",
      searchPlaceholder: "Search songs or artists...",
      allGenres: "All Genres",
      allLevels: "All Levels",
      songsForYou: "Songs for You",
      searchResults: "Search Results",
      allSongs: "All Songs",
      noSongs: "No songs found matching your criteria.",
      notAvailable: "Not Available Yet",
      notAvailableDesc: "Reach Phase 2 (Intermediate) to unlock the Song Library.",
      backToDashboard: "Back to Dashboard",
      nowPlaying: "Now Playing",
      genre: "Genre",
      key: "Key",
      bpm: "BPM",
      vocalRange: "Vocal Range",
      lyrics: "Lyrics",
      aiBackingTrack: "Song Preview",
      playPreview: "Play Song",
      pausePreview: "Pause",
      backingTrackSim: "Press Play to hear the full song",
      practiceSong: "Practice This Song",
      selectSongPlaceholder: "Select a song to see details and generate a backing track",
    },

    exerciseCard: {
      start: "Start",
      retry: "Retry",
      lastScore: "Last score",
      difficulty: { easy: "easy", medium: "medium", hard: "hard" },
    },

    phaseCard: {
      phaseLabel: (id) => `Phase ${id}`,
      features: "Features",
      more: (n) => `+${n} more`,
    },
  },

  zh: {
    // Sidebar
    appTagline: "您的京剧教练",
    nav: {
      dashboard: "主页",
      learningPaths: "学习路径",
      practice: "练习",
      voiceAnalysis: "声音分析",
      routinePlanner: "课程规划",
      learningPhases: "学习阶段",
      foundation: "基础功",
      technique: "行腔技法",
      performance: "舞台演绎",
      songLibrary: "唱段库",
      virtualStage: "虚拟舞台",
    },
    // Dashboard header
    welcomeBack: "欢迎回来",
    phaseJourney: (phase) => `第 ${phase} 阶段 · 京剧学习之旅`,
    // Stats cards
    dayStreak: "连续天数",
    weeklyGoal: "本周目标",
    practiceMinutes: "练习时长",
    avgScore: "平均评分",
    // Dashboard sections
    activeMission: "当前任务：基础功入门",
    activeMissionDesc: (phase) =>
      `完成第 ${phase} 阶段全部练习，解锁下一阶段。`,
    goToPhase: (phase) => `前往第 ${phase} 阶段`,
    continuePhase: (phase) => `继续第 ${phase} 阶段`,
    startTodayPractice: "开始今日练习",
    browseSongs: "浏览唱段",
    recentActivity: "近期活动",
    noRecentActivity: "暂无练习记录，快去练习吧！",
    completed: "已完成",
    score: "评分",
    yourProgress: "您的进度",
    weeklyPractice: "本周练习",
    minutes: "分钟",
    of: "/",
    goal: "目标",
    // Phase names in sidebar
    phase1Title: "基础功",
    phase2Title: "行腔技法",
    phase3Title: "舞台演绎",
    // Quick actions
    quickActions: "快捷操作",
    yourLearningPath: "学习阶段",
    startPracticeLabel: "开始练习",
    voiceExercises: "声乐练习",
    routinePlannerLabel: "课程规划",
    createPracticePlan: "制定练习计划",
    learningPathsLabel: "学习路径",
    chooseApproach: "选择您的学习方式",
    browseSongsLabel: "浏览唱段",
    findSongs: "查找练习曲目",
    virtualStageLabel: "虚拟舞台",
    performSong: "演唱一首曲目",
    minutesThisWeek: "本周练习时长",
    averageScore: "平均评分",
    viewAll: "查看全部",
    // Language toggle label
    toggleLabel: "EN",

    // Dashboard learning path config (banner summaries)
    lpc: {
      structured: {
        description: "继续您的京剧系统学习 — 丹田呼吸、咬字归韵与阶段进阶。",
        action: (phase) => `继续第 ${phase} 阶段`,
      },
      intensive: {
        description: "坚持每日旦角训练！专注假声控制、行腔流畅度与花腔装饰技法。",
        action: "开始今日练习",
      },
      performance: {
        description: "专攻生角唱段与舞台表现力，将二黄/西皮技法融入经典京剧唱腔。",
        action: (phase) => phase >= 2 ? "浏览唱段" : "开始练习",
      },
      adaptive: {
        description: "您的AI京剧课程已就绪！针对当前咬字与行腔弱点的专项练习。",
        action: "查看课程",
      },
      flexible: {
        description: "零压力京剧探索。自由选择任意唱段或练习，按自己节奏发现您的行当。",
        action: "浏览唱段",
      },
    },

    // Settings page
    settings: {
      title: "设置",
      profileSettings: "个人资料",
      manageProfile: "管理您的个人信息",
      name: "姓名",
      emailAddress: "电子邮件",
      experienceLevel: "经验水平",
      selectExperience: "选择经验水平",
      beginner: "初学者",
      intermediate: "中级",
      advanced: "高级",
      saving: "保存中...",
      saveChanges: "保存更改",
      resetPassword: "重置密码",
      updateSecurity: "更新您的账户安全设置",
      newPassword: "新密码",
      passwordPlaceholder: "最少8位，含A-Z、a-z、0-9、!@#",
      appearance: "外观",
      customizeApp: "自定义应用外观",
      darkMode: "深色模式",
      lightMode: "浅色模式",
      switchTheme: "切换深色/浅色主题",
      accountActions: "账户操作",
      manageAccount: "管理您的账户访问和数据",
      signOut: "退出登录",
      signOutDesc: "退出当前会话",
      resetProgress: "重置进度",
      resetProgressDesc: "删除所有练习记录并重新开始",
      resetAllProgress: "重置所有进度",
      resetConfirm: "确定要重置所有进度吗？此操作不可撤销。",
      savedTitle: "设置已保存",
      savedDesc: "您的个人资料已更新。",
      errorTitle: "错误",
      errorDesc: "保存设置失败，请重试。",
      progressResetTitle: "进度已重置",
      progressResetDesc: "您的学习进度已重置。",
      passwordUpdatedTitle: "密码已更新",
      passwordUpdatedDesc: "您的密码已成功更改。",
      invalidPasswordTitle: "密码无效",
      passwordErrorDesc: "更新密码失败，请重试。",
    },

    // Learning Paths page
    lp: {
      pageTitle: "选择您的",
      pageTitleHighlight: "学习路径",
      pageDesc: "选择符合您行当类型、经验水平和艺术目标的京剧训练方法。每条路径均根植于正宗的京剧传统。",
      backToDashboard: "返回主页",
      recommendedFor: (level) => `为${level}推荐`,
      recommendedDesc: (name) => `根据您的经验水平，我们推荐 ${name} 方法，以最大化您的学习潜力。`,
      recommended: "推荐",
      focusAreas: "重点领域：",
      approach: "训练方法：",
      benefits: "学习收益：",
      selected: "已选择",
      selectPath: "选择此路径",
      readyToStart: "准备好开始您的学习之旅了吗？",
      configuring: "配置中...",
      launchPath: "开始学习",
      notSureTitle: "不确定选哪条京剧路径？",
      notSureDesc1: "无需担心 — 您随时可以切换路径。如果您是京剧或中国古典演唱的新手，建议从京剧基础开始，打好技术基础。如果您已有一定经验并希望获得个性化辅导，可尝试AI 自适应京剧教练。",
      notSureDesc2: "每条路径都以正宗京剧技法为基础 — 丹田呼吸、咬字归韵、行腔、拖腔、韵味与神韵。选择最令您心动的方式，开启迈向京剧舞台的旅程。",
      selectedToastTitle: "学习路径已选择！",
      selectedToastDesc: (name) => `您已选择${name}。开始您的学习之旅吧！`,
      errorTitle: "错误",
      errorDesc: "保存学习路径失败，请重试。",
      paths: {
        structured: {
          name: "京剧基础",
          description: "系统学习京剧声乐基础 — 从丹田呼吸支撑、咬字到行腔与韵味",
          duration: "12-16周",
          difficulty: "初学到高级",
          focus: ["京剧基础", "板眼节奏", "阶段进阶"],
          approach: "线性递进学习京剧各阶段：基础功 → 行腔技法 → 唱段曲目，每阶段设有明确里程碑",
          benefits: ["建立正宗京剧演唱技法", "涵盖丹田呼吸、咬字、拖腔", "旦角/生角嗓音系统训练", "适合京剧完全初学者"],
        },
        intensive: {
          name: "旦角强化",
          description: "快速掌握旦角技法 — 每日高强度训练，专注程式化女性嗓音、假声控制与行腔",
          duration: "4-6周",
          difficulty: "中级",
          focus: ["旦角嗓音", "假声控制", "每日训练"],
          approach: "集中每日练习，攻克最关键的旦角技法：假声区、换声区、颤音控制与花腔装饰",
          benefits: ["快速发展旦角嗓音", "假声区强化训练", "每日行腔与拖腔练习", "梅派/程派风格入门"],
        },
        performance: {
          name: "生角强化",
          description: "深入生角声乐修炼 — 老生胸腔共鸣、小生抒情音色，以及男性行当端庄的二黄/西皮腔",
          duration: "8-12周",
          difficulty: "适合所有水平",
          focus: ["老生唱法", "二黄西皮", "舞台表现"],
          approach: "通过经典唱段掌握生角演唱技法 — 老生胸腔混声、快板咬字与男性京剧的高贵韵味",
          benefits: ["正宗老生/小生嗓音发展", "二黄与西皮旋律掌握", "念白与韵白戏剧训练", "生角经典唱段演唱准备"],
        },
        adaptive: {
          name: "AI 自适应京剧教练",
          description: "个性化AI辅导，针对您的京剧具体弱点 — 无论是咬字、行腔、韵味还是呼吸支撑",
          duration: "灵活",
          difficulty: "适合所有水平",
          focus: ["弱点专攻", "AI引导", "京剧指标"],
          approach: "AI分析您的京剧专项指标（音准、咬字清晰度、颤音、韵味），生成定制练习序列",
          benefits: ["根据行当类型定制（旦/生/净）", "精准攻克您的京剧弱点", "融合二胡意识的智能辅导", "按您的嗓音优化训练节奏"],
        },
        flexible: {
          name: "唱段先行",
          description: "通过演唱实际唱段学习京剧技法 — 从苏三起解到霸王别姬再到锁麟囊",
          duration: "自主节奏",
          difficulty: "适合所有水平",
          focus: ["唱段驱动", "舞台表现", "自主探索"],
          approach: "通过经典唱段掌握京剧技法 — 技法服务于人物和剧情，而非相反",
          benefits: ["即时唱段实践应用", "京剧舞台表演自信", "人物塑造与神韵培养", "灵活自主节奏探索"],
        },
      },
    },

    // Analysis page
    analysis: {
      title: "声音分析",
      subtitle: "上传您的演唱录音，获取深度声学分析和专业反馈。",
      chooseFile: "选择音频文件",
      dragDrop: "将您的演唱录音拖放至此，或点击浏览。支持 WAV、MP3、M4A 和 WEBM 格式。",
      invalidFile: "请选择有效的音频文件。",
      invalidFileDrop: "请拖放有效的音频文件。",
      analyzeVoice: "分析声音",
      analyzingTitle: "正在分析您的声音",
      analyzingDesc: "AI正在处理您的音准、音色与技法，通常需要5-10秒。",
      analysisComplete: "分析完成",
      resultsGenerated: (date) => `分析结果生成于 ${date}`,
      analyzeNewFile: "分析新文件",
      expertInsights: "专家建议",
      defaultSuggestions: [
        "您的音准在整段录音中保持稳定一致。",
        "音色稳定性较强，显示出良好的声带控制能力。",
        "建议在高音段落时注重呼吸支撑。",
      ],
      openPractice: "开始练习课程",
      howItWorks: "工作原理",
      howItWorksDesc: "基于信号处理的专业分析",
      steps: [
        { title: "声学指标引擎", desc: "我们提取基频（F0）和频谱特征来衡量音准与音色。" },
        { title: "AI声乐辅导", desc: "AI模型分析录音，提供自然语言反馈和改进建议。" },
        { title: "渐进式跟踪", desc: "每次分析结果均保存至您的档案，帮助您追踪声乐成长进度。" },
      ],
      bestTips: "最佳录音技巧",
      tips: [
        "使用安静环境，尽量减少背景噪音。",
        "与麦克风保持约15-30厘米的距离。",
        "清晰、自然地演唱。",
      ],
    },

    // Routine Planner page
    routine: {
      title: "练习课程规划",
      subtitle: "根据您的目标和进度生成个性化练习课程",
      generateTitle: "生成课程",
      generateDesc: "自定义您的练习课",
      duration: "时长",
      durationTip: "建议：每次20-40分钟",
      focusAreas: "重点领域",
      focusAreasTip: "留空则生成均衡课程",
      generating: "生成中...",
      generate: "生成课程",
      yourRoutines: "您的练习课程",
      minuteSession: (n) => `${n}分钟练习课`,
      exercisesCount: (total, completed) => `${total}个练习 • 已完成${completed}个`,
      progress: "进度",
      start: "开始",
      noRoutines: "暂无课程",
      noRoutinesDesc: "生成您的第一个练习课程，开始有计划的练习",
      categories: {
        warmup: "热身",
        technique: "技法",
        performance: "演唱",
      },
    },

    // Phase page
    phase: {
      pageTitle: (id, name) => `第 ${id} 阶段：${name}`,
      complete: "已完成",
      notAvailable: "阶段未开放",
      notAvailableDesc: "完成前面的阶段以解锁此内容。",
      backToDashboard: "返回主页",
      finalTest: (id) => `第 ${id} 阶段终试`,
      availableNow: "现已开放",
      finalTestDesc: "将本阶段所学融为一体。此次演唱将作为您的阶段最终评分依据。",
      startTest: "开始阶段测试",
      exercises: "练习曲目",
      exercisesCompleted: (done, total) => `${done}/${total} 已完成`,
      noExercises: "暂无练习曲目，请稍后查看！",
      whatYoullLearn: "您将学到",
      nextPhase: "下一阶段",
      goToPhase: (n) => `前往第 ${n} 阶段`,
    },

    // Practice page
    practice: {
      titleSong: (title) => `练习：${title}`,
      titleVoice: "声乐练习",
      subtitleSong: (artist, genre, key, bpm) => `${artist} • ${genre} • ${key} • ${bpm} BPM`,
      subtitleVoice: "录制您的声音并获得即时AI智能反馈",
      important: "注意：",
      micWarning: "录音前请将麦克风放置在附近。建议录音时长超过20秒，以获得更准确的AI分析结果。",
      songPracticeMode: "唱段练习模式",
      difficulty: "难度",
      vocalRange: "音域",
      key: "调式",
      tempo: "板式速度",
      practiceTipsTitle: "💡 练习技巧：",
      practiceTips: (key, bpm) => [
        "演唱前先做热嗓练习",
        `专注于调式 (${key}) 的音准`,
        `保持 ${bpm} BPM 的稳定板速`,
        "多次录音以追踪您的进步",
      ],
      pathModes: {
        flexible: { title: "唱段先行模式", desc: "今天随心选择任意唱段或练习。无压力 — 自由探索京剧！" },
        competitive: { title: "挑战模式已开启", desc: "完成练习以获得成就并升级！" },
        intensive: { title: "旦角强化", desc: "专注每日旦角训练，咬字与行腔的一致性是关键！" },
        performance: { title: "生角强化", desc: "专攻生角唱段与舞台技能，构建您的二黄/西皮曲目！" },
        adaptive: { title: "AI 自适应京剧教练", desc: "基于您咬字、行腔、韵味进度的AI智能京剧推荐。" },
        structured: { title: "京剧基础", desc: "系统化地跟随渐进式京剧路径逐阶学习。" },
      },
      singTitle: (title) => `演唱：${title}`,
      voiceRecorder: "录音器",
      practiceDesc: "演唱此曲目并获得AI对您表现的反馈",
      selectExercise: "选择练习曲目或自由录音",
      instructions: "练习说明",
      demo: "演示",
      upload: "上传",
      analyzing: "分析中...",
      analyzeVoice: "分析声音",
      analysisResults: "分析结果",
      aiCoach: "AI声乐教练分析",
      defaultFeedback: "您的演唱已完成评估。下次练习请专注于稳定的技法和呼吸支撑。",
      technicalStrengths: "技术优势",
      detectedMistakes: "检测到的技术问题",
      suggestions: "改进建议",
      tryAgain: "再试一次",
      exercises: "练习曲目",
      practiceSavedTitle: "练习已保存！",
      practiceSavedDesc: "您的连续天数已更新。",
      sessionExpiredTitle: "会话已过期",
      sessionExpiredDesc: "请重新登录以保存您的进度。",
      exerciseNotFoundTitle: "练习曲目未找到",
      exerciseNotFoundDesc: "此练习曲目不再存在，请选择新的练习。",
      saveFailedTitle: "无法保存进度",
      saveFailedDesc: "您的练习已分析但未记录，请重试。",
    },

    // Learning Path Welcome page
    lpWelcome: {
      confirmed: "路径已确认",
      welcomeTo: (title) => `欢迎踏上 ${title} 之路`,
      whatsAhead: "接下来：",
      startTraining: "开始第一次训练",
      changePath: "更换路径",
      goToDashboard: "前往主页",
      paths: {
        structured: {
          description: "系统化京剧基础学习：丹田呼吸、咬字归韵、旦角/生角嗓音入门与五声音阶音准训练。",
          highlights: ["丹田呼吸与咬字练习", "适合京剧初学者", "系统化三阶段进阶"],
        },
        intensive: {
          description: "快速掌握旦角技法，每日高强度训练专攻假声控制、行腔与花腔装饰。",
          highlights: ["每日旦角假声训练", "行腔与拖腔强化练习", "梅派/程派风格发展"],
        },
        performance: {
          description: "深入生角声乐修炼 — 老生胸腔共鸣、二黄/西皮腔韵，以及男性京剧行当的端庄演绎。",
          highlights: ["老生/小生嗓音发展", "二黄与西皮旋律掌握", "经典唱段演唱准备"],
        },
        adaptive: {
          description: "个性化AI学习路径，精准攻克您的京剧弱点 — 咬字、行腔、韵味或呼吸支撑。",
          highlights: ["AI驱动的京剧推荐", "精准攻克您的弱点技法", "行当（旦/生/净）感知辅导"],
        },
        flexible: {
          description: "通过演唱实际唱段学习京剧技法 — 从苏三起解到霸王别姬再到锁麟囊，按您的节奏进行。",
          highlights: ["经典唱段驱动学习", "自主京剧探索", "人物塑造与神韵培养"],
        },
      },
    },

    // Perform (Virtual Stage) page
    perform: {
      notAvailable: "尚未开放",
      notAvailableDesc: "升至第3阶段（高级）即可解锁虚拟舞台。",
      backToDashboard: "返回主页",
      finalTestTitle: (phase) => `第 ${phase} 阶段终试`,
      stageTitle: "虚拟演出舞台",
      finalTestDesc: (title) => `演唱"${title}"，展示您的学习成果`,
      stageDesc: "通过模拟观众反馈练习舞台演出",
      finalTestBadge: "阶段终试",
      micWarning: "录音前请将麦克风放置在附近。建议录音时长超过20秒，以获得更准确的AI分析结果。",
      important: "注意：",
      readyToSing: (title) => `准备好演唱"${title}"了吗？`,
      readyToPerform: "准备好登台了吗？",
      songSubtitle: (artist, genre) => `${artist} - ${genre}`,
      stepOnStage: "踏上虚拟舞台，展示您的演唱实力",
      takeStage: "登台演唱",
      micLevel: "话筒音量",
      tooQuiet: "🔇 声音太小",
      tooLoud: "🔊 声音太大",
      goodLevel: "✓ 音量适中",
      endPerformance: "结束演出",
      analyzingTitle: "正在分析演出",
      analyzingDesc: "观众正在聆听...",
      audienceReaction: "观众反应",
      retry: "重试",
      yourRecording: "您的录音",
      performAgain: "再次演出",
      phaseComplete: "阶段完成！",
      phaseUnlocked: (phase) => `恭喜！您已解锁第 ${phase} 阶段`,
      goToPhase: (phase) => `前往第 ${phase} 阶段`,
      performanceScore: "演出评分",
      performanceTips: "演出技巧",
      tips: [
        "开嗓 — 开始前用轻柔的滑音热嗓",
        "丹田呼吸 — 用腹部呼吸，而非胸腔",
        "咬字 — 每个字的声母要清晰有力",
        "韵味 — 沉浸于您的行当（旦/生/净），让情感塑造音色",
        "叫好 — 想象台下戏迷随时准备高呼\"好！\"",
      ],
    },

    // Songs page
    songs: {
      title: "京剧唱段库",
      subtitle: "查找符合您行当类型（旦角/生角/净角）和阶段的经典唱段",
      searchPlaceholder: "搜索唱段或演唱者...",
      allGenres: "所有类型",
      allLevels: "所有级别",
      songsForYou: "为您推荐",
      searchResults: "搜索结果",
      allSongs: "全部唱段",
      noSongs: "未找到符合条件的唱段。",
      notAvailable: "尚未开放",
      notAvailableDesc: "升至第2阶段（中级）即可解锁唱段库。",
      backToDashboard: "返回主页",
      nowPlaying: "正在播放",
      genre: "类型",
      key: "调式",
      bpm: "板式速度",
      vocalRange: "音域",
      lyrics: "唱词",
      aiBackingTrack: "唱段预览",
      playPreview: "播放唱段",
      pausePreview: "暂停",
      backingTrackSim: "点击播放完整唱段",
      practiceSong: "练习此唱段",
      selectSongPlaceholder: "选择唱段以查看详情并生成伴奏",
    },

    exerciseCard: {
      start: "开始",
      retry: "重练",
      lastScore: "上次得分",
      difficulty: { easy: "简单", medium: "中等", hard: "困难" },
    },

    phaseCard: {
      phaseLabel: (id) => `第 ${id} 阶段`,
      features: "内容特色",
      more: (n) => `+${n} 更多`,
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  // Restore saved preference on mount; fall back to "en" if nothing saved
  useEffect(() => {
    const saved = localStorage.getItem("app-lang");
    if (saved === "zh" || saved === "en") setLang(saved);
    else localStorage.setItem("app-lang", "en");
  }, []);

  const setLanguage = (next) => {
    if (next !== "en" && next !== "zh") return;
    setLang(next);
    localStorage.setItem("app-lang", next);
  };

  // keep toggle for any legacy callers
  const toggle = () => setLanguage(lang === "en" ? "zh" : "en");

  return (
    <LanguageContext.Provider value={{ lang, toggle, setLanguage, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
